/**
 * Auto-generated by scripts/check-electron-mock-coverage.ts — DO NOT edit by hand.
 * Consumer files: apps/electron/src/main/browser-pane-manager.ts.
 * Run `bun scripts/check-electron-mock-coverage.ts` to refresh.
 */

export const coverageSnapshot = {
  "BrowserWindow": ["addBrowserView","destroy","focus","getContentSize","hide","isDestroyed","isMinimized","isResizable","on","restore","setContentSize","setResizable","setTopBrowserView","show","showInactive","webContents"],
  "BrowserView": ["setAutoResize","setBounds","webContents"],
  "WebContents": ["canGoBack","canGoForward","capturePage","executeJavaScript","getTitle","getURL","goBack","goForward","id","isDestroyed","loadFile","loadURL","on","once","reload","removeListener","send","sendInputEvent","session","setUserAgent","setWindowOpenHandler","stop","userAgent"]
} as const
