import { describe, expect, it } from 'bun:test'
import {
  endpointProviderDisplayName,
  migrateAutogeneratedProviderName,
  piAuthProviderDisplayName,
  providerConnectionName,
} from './connection-names.ts'

describe('provider connection names', () => {
  it('maps provider keys to real display names', () => {
    expect(piAuthProviderDisplayName('google')).toBe('Google AI Studio')
    expect(piAuthProviderDisplayName('openrouter')).toBe('OpenRouter')
    expect(piAuthProviderDisplayName('unknown')).toBeNull()
  })

  it('keeps provider-only names for duplicate slugs', () => {
    expect(providerConnectionName('openrouter')).toBe('OpenRouter')
    expect(providerConnectionName('unknown')).toBeNull()
  })

  it('derives readable custom endpoint names', () => {
    expect(endpointProviderDisplayName('https://apihub.agnes-ai.com/v1')).toBe('Agnes AI')
    expect(endpointProviderDisplayName('https://api.openai.com/v1')).toBe('OpenAI')
    expect(endpointProviderDisplayName('not a url')).toBeNull()
  })

  it('migrates legacy autogenerated names', () => {
    expect(migrateAutogeneratedProviderName({
      name: 'ARCHstudio Backend (API Key) 2',
      slug: 'pi-api-key-2',
      providerType: 'pi',
      piAuthProvider: 'openrouter',
    })).toBe('OpenRouter')

    expect(migrateAutogeneratedProviderName({
      name: 'ARCHstudio Backend (API Key) 2',
      slug: 'pi-api-key-2',
      providerType: 'pi_compat',
      piAuthProvider: 'openai',
      baseUrl: 'https://apihub.agnes-ai.com/v1',
      customEndpoint: { api: 'openai-completions' },
    })).toBe('Agnes AI')

    expect(migrateAutogeneratedProviderName({
      name: 'ARCHstudio Backend (OpenRouter)',
      slug: 'pi-api-key',
      providerType: 'pi',
      piAuthProvider: 'openrouter',
    })).toBe('OpenRouter')
  })

  it('preserves custom, OAuth, and explicitly named endpoint names', () => {
    expect(migrateAutogeneratedProviderName({
      name: 'My OpenRouter',
      slug: 'pi-api-key',
      providerType: 'pi',
      piAuthProvider: 'openrouter',
    })).toBeNull()

    expect(migrateAutogeneratedProviderName({
      name: 'ChatGPT Plus',
      slug: 'chatgpt-plus',
      providerType: 'pi',
      piAuthProvider: 'openai-codex',
    })).toBeNull()

    expect(migrateAutogeneratedProviderName({
      name: 'Manifest',
      slug: 'pi-api-key',
      providerType: 'pi_compat',
      piAuthProvider: 'openai',
      customEndpoint: { api: 'openai-completions' },
    })).toBeNull()
  })
})
