const PI_AUTH_PROVIDER_DISPLAY_NAMES: Record<string, string> = {
  anthropic: 'Anthropic',
  openai: 'OpenAI',
  'openai-codex': 'OpenAI',
  google: 'Google AI Studio',
  openrouter: 'OpenRouter',
  'azure-openai-responses': 'Azure OpenAI',
  'amazon-bedrock': 'Amazon Bedrock',
  groq: 'Groq',
  mistral: 'Mistral',
  xai: 'xAI',
  cerebras: 'Cerebras',
  zai: 'z.ai',
  huggingface: 'Hugging Face',
  minimax: 'Minimax',
  'minimax-cn': 'Minimax CN',
  'kimi-coding': 'Kimi (Coding)',
  'vercel-ai-gateway': 'Vercel AI Gateway',
}

const OAUTH_PROVIDER_KEYS = new Set(['openai-codex', 'github-copilot'])

export function piAuthProviderDisplayName(piAuthProvider: string): string | null {
  return PI_AUTH_PROVIDER_DISPLAY_NAMES[piAuthProvider] ?? null
}

export function providerConnectionName(piAuthProvider: string): string | null {
  return piAuthProviderDisplayName(piAuthProvider)
}

const PROVIDER_WORDS: Record<string, string> = {
  ai: 'AI',
  api: 'API',
  openai: 'OpenAI',
  xai: 'xAI',
}

export function endpointProviderDisplayName(baseUrl: string): string | null {
  try {
    const labels = new URL(baseUrl).hostname.toLowerCase().split('.').filter(Boolean)
    if (labels.length < 2) return null
    const commonSecondLevel = new Set(['co', 'com', 'net', 'org'])
    const domainIndex = labels.length > 2 && commonSecondLevel.has(labels.at(-2) ?? '') ? -3 : -2
    const domain = labels.at(domainIndex)
    if (!domain) return null
    return domain
      .split(/[-_]+/)
      .filter(Boolean)
      .map((word) => PROVIDER_WORDS[word] ?? `${word[0]?.toUpperCase() ?? ''}${word.slice(1)}`)
      .join(' ') || null
  } catch {
    return null
  }
}

export function migrateAutogeneratedProviderName(connection: {
  name: string
  slug: string
  providerType: string
  piAuthProvider?: string
  baseUrl?: string
  customEndpoint?: unknown
}): string | null {
  const provider = connection.piAuthProvider
  if (
    (connection.providerType !== 'pi' && connection.providerType !== 'pi_compat')
    || !provider
    || OAUTH_PROVIDER_KEYS.has(provider)
  ) {
    return null
  }

  const providerName = piAuthProviderDisplayName(provider)
  const migratedName = connection.customEndpoint && connection.baseUrl
    ? endpointProviderDisplayName(connection.baseUrl)
    : providerName
  if (!migratedName) return null

  const numericSuffix = '(?: \\d+)?'
  const generatedNames = [new RegExp(`^ARCHstudio Backend \\(API Key\\)${numericSuffix}$`)]
  if (providerName) {
    const escapedProviderName = providerName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    generatedNames.push(new RegExp(`^ARCHstudio Backend \\(${escapedProviderName}\\)${numericSuffix}$`))
  }
  if (!generatedNames.some((pattern) => pattern.test(connection.name))) return null

  return migratedName
}
