name = "g4os-viewer"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "SESSIONS_BUCKET"
bucket_name = "g4os-shared-sessions"

[[r2_buckets]]
binding = "RELEASES_BUCKET"
bucket_name = "g4os-releases"
