/**
 * Auto-generated by scripts/check-electron-mock-coverage.ts — DO NOT edit by hand.
 * Consumer file scanned: apps/electron/src/main/browser-pane-manager.ts. Run 'bun scripts/check-electron-mock-coverage.ts' to refresh.
 *
 * Required = union of every BrowserWindow / BrowserView / WebContents member
 * accessed by the consumers above. The browser-pane-manager test asserts at
 * module-load time that every entry here exists on the corresponding mock
 * instance. Drift (real code adds a new BrowserWindow.setVisibleOnAllWorkspaces call,
 * the mock does not expose it) raises a top-level MockCoverageError.
 */

export const REQUIRED_ELECTRON_MEMBERS = {
  "BrowserWindow": [
    "addBrowserView",
    "destroy",
    "focus",
    "getContentSize",
    "hide",
    "isDestroyed",
    "isMinimized",
    "isResizable",
    "on",
    "restore",
    "setContentSize",
    "setResizable",
    "setTopBrowserView",
    "show",
    "showInactive",
    "webContents"
  ],
  "BrowserView": [
    "setAutoResize",
    "setBounds",
    "webContents"
  ],
  "WebContents": [
    "canGoBack",
    "canGoForward",
    "capturePage",
    "executeJavaScript",
    "getTitle",
    "getURL",
    "goBack",
    "goForward",
    "id",
    "isDestroyed",
    "loadFile",
    "loadURL",
    "on",
    "once",
    "reload",
    "removeListener",
    "send",
    "sendInputEvent",
    "session",
    "setUserAgent",
    "setWindowOpenHandler",
    "stop",
    "userAgent"
  ]
} as const
