#!/usr/bin/env bun
/**
 * scripts/gen-test-snapshots.ts
 *
 * Scans the repo for `*.test.{ts,tsx}` files, locates top-level
 * `const EXPECTED_*` / `const SNAPSHOT_*` array declarations, and
 * extracts them into co-located `__snapshots__/<test-name>.snap.ts`
 * files with an `// Auto-generated` header.
 *
 * The test file is rewritten so the array is imported from the snap
 * file instead of being declared inline.
 *
 * Why? Snapshot-style test constants are checked-in infrastructure,
 * not test setup.  Putting them in a separate file (a) signals that
 * intent to future contributors, (b) keeps test files focused on
 * assertions, and (c) lets a single tool do the extraction for any
 * future snapshot-style test — instead of a manual camera dance.
 *
 * Usage:
 *   bun run scripts/gen-test-snapshots.ts          # scan & generate
 *   bun run scripts/gen-test-snapshots.ts --dry     # preview only
 *   bun run scripts/gen-test-snapshots.ts --check   # exit 1 if stale
 *
 * Wire into package.json:
 *   "gen-snapshots": "bun run scripts/gen-test-snapshots.ts",
 *   "gen-snapshots:check": "bun run scripts/gen-test-snapshots.ts --check"
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from 'node:fs'
import { join, relative, basename, dirname, resolve } from 'node:path'


// ── Config ──────────────────────────────────────────────────────────────

const ROOT = resolve(import.meta.dir, '..')

/** Regex to match a top-level const EXPECTED_* or SNAPSHOT_* declaration.
 *  Captures the full declaration including type annotation and value.
 *  Accepts any array type (readonly string[], string[], readonly any[], etc.).
 *  NOTE: The non-greedy [\s\S]*?] stops at the first closing bracket,
 *  so nested arrays (e.g. [[1],[2]]) won't match correctly.  This is
 *  intentional — the tool targets flat string[] snapshot arrays only. */
const SNAPSHOT_CONST_RE =
  /^(export\s+)?const\s+((?:EXPECTED|SNAPSHOT)_[A-Z_0-9]+)\s*(?::\s*(?:readonly\s+)?[\w\[\]\s|]+)?\s*=\s*(\[[\s\S]*?\])\s*(?:as\s+const)?\s*;/gm

/** Directories to skip entirely */
const SKIP_DIRS = new Set([
  'node_modules',
  '.git',
  'dist',
  '.next',
  '.cache',
])

// ── Helpers ─────────────────────────────────────────────────────────────

interface Extraction {
  /** Absolute path to the test file */
  testFile: string
  /** The constant name, e.g. 'EXPECTED_CHANNELS' */
  constName: string
  /** The full declaration text (const ... = [...];) */
  declaration: string
  /** The array body text (everything between [ and ]) */
  arrayBody: string
}

/**
 * Walk a directory tree and return relative paths of all test files.
 */
const TEST_FILE_RE = /\.test\.(ts|tsx)$/;

function findTestFilesSync(dir: string): string[] {
  const found: string[] = [];
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return found;
  }
  for (const name of entries) {
    if (SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    let st: ReturnType<typeof statSync>;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      found.push(...findTestFilesSync(full));
    } else if (TEST_FILE_RE.test(name)) {
      found.push(relative(ROOT, full));
    }
  }
  return found;
}

function findTestFiles(): string[] {
  return findTestFilesSync(ROOT);
}

/**
 * Extract SNAPSHOT_* / EXPECTED_* const declarations from file content.
 */
function extractSnapshots(
  filePath: string,
  content: string,
): Extraction[] {
  const results: Extraction[] = []
  // Reset lastIndex for global regex
  SNAPSHOT_CONST_RE.lastIndex = 0

  let match: RegExpExecArray | null
  while ((match = SNAPSHOT_CONST_RE.exec(content)) !== null) {
    const fullMatch = match[0]
    const constName = match[2]
    const arrayBody = match[3]

    results.push({
      testFile: filePath,
      constName,
      declaration: fullMatch,
      arrayBody,
    })
  }

  return results
}

/**
 * Generate the snap file content with an auto-generated header.
 */
function generateSnapContent(extractions: Extraction[]): string {
  const lines: string[] = [
    '// ── Auto-generated by scripts/gen-test-snapshots.ts ────────────────',
    '// Do not edit by hand — re-run `bun run gen-snapshots` to regenerate.',
    '// ──────────────────────────────────────────────────────────────────',
    '',
  ]

  for (const ext of extractions) {
    // Rebuild the declaration with export keyword
    // Guard against double-export: only add export if not already present
    const decl = ext.declaration.replace(
      /^(export\s+)?const/,
      (m) => m.includes('export') ? m : 'export const',
    )
    lines.push(decl)
    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Rewrite the test file to import from the snap file instead of
 * declaring the array inline.
 */
function rewriteTestFile(
  content: string,
  extractions: Extraction[],
  snapImportPath: string,
): string {
  let result = content

  // Guard: skip if import already exists (prevents duplication on re-run)
  const namesToImport = extractions.map((e) => e.constName)
  const importLine = `import { ${namesToImport.join(', ')} } from '${snapImportPath}'`
  if (result.includes(importLine)) return result

  // Remove each inline declaration using line-by-line scanning
  // (more robust than regex over escaped declaration text)
  for (const ext of extractions) {
    result = removeDeclarationLineByLine(result, ext.constName)
  }

  // Add import at the top (after the last existing import)
  const lines = result.split('\n')
  let lastImportIdx = -1
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].match(/^\s*import\s/)) {
      lastImportIdx = i
    }
  }

  if (lastImportIdx >= 0) {
    lines.splice(lastImportIdx + 1, 0, importLine)
  } else {
    lines.unshift(importLine, '')
  }

  result = lines.join('\n')

  // Clean up multiple blank lines left by removal
  result = result.replace(/\n{3,}/g, '\n\n')

  return result
}


/**
 * Remove a const declaration from file content using line-by-line scanning.
 * More robust than regex over escaped declaration text — handles multi-line
 * declarations with varying whitespace, comments, and special characters.
 */
function removeDeclarationLineByLine(content: string, constName: string): string {
  const lines = content.split('\n')
  const result: string[] = []
  let i = 0
  while (i < lines.length) {
    const line = lines[i]!
    // Detect the start of the target declaration
    if (line.match(new RegExp(`^\s*(export\s+)?const\s+${constName}\b`))) {
      // Skip lines until we find the closing semicolon
      let depth = 0
      while (i < lines.length) {
        const l = lines[i]!
        // Count brackets to handle nested arrays/objects
        for (const ch of l) {
          if (ch === '[' || ch === '{' || ch === '(') depth++
          if (ch === ']' || ch === '}' || ch === ')') depth--
        }
        if (l.includes(';') && depth <= 0) {
          i++
          break
        }
        i++
      }
      // Skip trailing blank lines after the declaration
      while (i < lines.length && lines[i]!.trim() === '') i++
      continue
    }
    result.push(line)
    i++
  }
  return result.join('\n')
}

// ── Main ────────────────────────────────────────────────────────────────

interface CliOptions {
  dryRun: boolean
  checkMode: boolean
}

function parseArgs(): CliOptions {
  const args = process.argv.slice(2)
  return {
    dryRun: args.includes('--dry'),
    checkMode: args.includes('--check'),
  }
}

function main() {
  const opts = parseArgs()
  const testFiles = findTestFiles()

  console.log(`Scanning ${testFiles.length} test files for snapshot arrays...`)

  const allExtractions: Extraction[] = []
  const filesModified: string[] = []

  for (const relPath of testFiles) {
    const absPath = join(ROOT, relPath)
    const content = readFileSync(absPath, 'utf-8')
    const extractions = extractSnapshots(absPath, content)

    if (extractions.length > 0) {
      allExtractions.push(...extractions)
      filesModified.push(relPath)
    }
  }

  if (allExtractions.length === 0) {
    console.log('No snapshot arrays found. Nothing to generate.')
    process.exit(0)
  }

  console.log(`Found ${allExtractions.length} snapshot array(s) in ${filesModified.length} file(s):`)
  for (const ext of allExtractions) {
    const rel = relative(ROOT, ext.testFile)
    console.log(`  ${ext.constName} in ${rel}`)
  }

  // Group extractions by test file
  const byFile = new Map<string, Extraction[]>()
  for (const ext of allExtractions) {
    const existing = byFile.get(ext.testFile) || []
    existing.push(ext)
    byFile.set(ext.testFile, existing)
  }

  let anyChanges = false

  for (const [testFile, extractions] of byFile) {
    const testDir = dirname(testFile)
    const testBase = basename(testFile).replace(/\.(test|spec)\.(ts|tsx)$/, '')
    const snapDir = join(testDir, '__snapshots__')
    const snapFile = join(snapDir, `${testBase}.snap.ts`)
    const snapAbsPath = join(ROOT, snapFile)

    // Relative import path from test file to snap file
    const relFromTest = relative(
      dirname(testFile),
      snapFile,
    ).replace(/\\/g, '/').replace(/\.ts$/, '')

    // Generate snap file content
    const snapContent = generateSnapContent(extractions)

    // Read current test file content
    const testContent = readFileSync(join(ROOT, testFile), 'utf-8')

    // Rewrite test file to import from snap file
    const rewritten = rewriteTestFile(testContent, extractions, relFromTest)

    // Check if snap file already exists and matches
    if (existsSync(snapAbsPath)) {
      const existingSnap = readFileSync(snapAbsPath, 'utf-8')
      if (existingSnap === snapContent) {
        console.log(`  [skip] ${snapFile} — already up to date`)
      } else {
        console.log(`  [update] ${snapFile}`)
        if (!opts.dryRun) writeFileSync(snapAbsPath, snapContent)
        anyChanges = true
      }
    } else {
      console.log(`  [create] ${snapFile}`)
      if (!opts.dryRun) {
        mkdirSync(snapDir, { recursive: true })
        writeFileSync(snapAbsPath, snapContent)
      }
      anyChanges = true
    }

    // Check if test file needs rewriting
    if (rewritten !== testContent) {
      if (opts.checkMode) {
        console.log(`  [stale] ${testFile} — needs import rewrite`)
        anyChanges = true
      } else if (opts.dryRun) {
        console.log(`  [would-rewrite] ${testFile}`)
        anyChanges = true
      } else {
        console.log(`  [rewrite] ${testFile}`)
        writeFileSync(join(ROOT, testFile), rewritten)
        anyChanges = true
      }
    }
  }

  if (opts.checkMode && anyChanges) {
    console.error('\nSnapshot files are stale. Run `bun run gen-snapshots` to regenerate.')
    process.exit(1)
  }

  if (opts.dryRun) {
    console.log('\nDry run — no files modified.')
  } else {
    console.log(`\nDone. ${filesModified.length} file(s) processed, ${allExtractions.length} snapshot(s) generated.`)
  }
}

main()
