#!/usr/bin/env bun
/**
 * scripts/ipc-inventory.ts
 *
 * Reads every wire-format string value from RPC_CHANNELS in
 * packages/shared/src/protocol/channels.ts, sorts them, and formats them
 * into an EXPECTED_CHANNELS: string[] = [...] block fenced by
 * auto-generated comments.
 *
 * Behaviour:
 *   --check   (default, CI)  Exit 1 if the on-disk file differs from what
 *                             we'd generate.  No writes.
 *   --write   Write the regenerated block back to the target file.
 *
 * Target file: apps/electron/src/shared/__tests__/ipc-channels.test.ts
 *
 * The generated block lives between two sentinel comments:
 *   // GENERATED BY scripts/ipc-inventory.ts -- DO NOT EDIT BELOW
 *   // GENERATED BY scripts/ipc-inventory.ts -- DO NOT EDIT ABOVE
 *
 * When the sentinel region doesn't exist yet (--write will create it at
 * the end of the file).
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

// ── Paths ──────────────────────────────────────────────────────────────

const ROOT = resolve(import.meta.dir, '..')
const CHANNELS_SRC = resolve(
  ROOT,
  'packages/shared/src/protocol/channels.ts',
)
const TARGET_TEST = resolve(
  ROOT,
  'apps/electron/src/shared/__tests__/ipc-channels.test.ts',
)

// ── Sentinel fences ────────────────────────────────────────────────────

const FENCE_OPEN =
  '// GENERATED BY scripts/ipc-inventory.ts -- DO NOT EDIT BELOW'
const FENCE_CLOSE =
  '// GENERATED BY scripts/ipc-inventory.ts -- DO NOT EDIT ABOVE'

// ── Extract all string values from RPC_CHANNELS ────────────────────────
//
// The object is nested: each namespace has KEY: 'value' entries.
// We grab every single-quoted or double-quoted string literal that sits
// after a colon + optional whitespace — i.e. the wire-format values.

function extractChannelValues(src: string): string[] {
  // Match lines like:  GET: 'sessions:get',   or   CREATE: 'server:createWorkspace',
  // We look for:  identifier : ['"]...['"]
  // Skip lines that are comments-only (they won't match the pattern).
  const values: string[] = []
  for (const line of src.split('\n')) {
    const trimmed = line.trim()
    // Skip comments and blank lines
    if (trimmed.startsWith('//') || trimmed.startsWith('*') || !trimmed) continue
    // Match:  IDENTIFIER: 'value',  or  IDENTIFIER: "value",
    // Digits are part of the key charset — `GET_ENABLE_1M_CONTEXT` is a real
    // channel key, and an `[A-Z_]+`-only class silently dropped it (and its
    // setter) from the inventory.
    const m = trimmed.match(
      /^[A-Z0-9_]+\s*:\s*(['"])([^'"]+)\1\s*,?\s*(?:\/\/.*)?$/,
    )
    if (m) {
      values.push(m[2])
    }
  }
  return values
}

// ── Format the EXPECTED_CHANNELS block ─────────────────────────────────

function formatBlock(values: string[]): string {
  const sorted = [...values].sort()
  const lines: string[] = [
    '',
    FENCE_OPEN,
    '// Sorted wire-format strings from RPC_CHANNELS (packages/shared/src/protocol/channels.ts).',
    '// Used by the ipc-channels test to assert every channel is accounted for.',
    `// Last regenerated: ${new Date().toISOString()}`,
    `// Channel count: ${sorted.length}`,
    '',
    'const EXPECTED_CHANNELS: string[] = [',
  ]

  // Print in columns of 3 for readability
  const COLS = 3
  for (let i = 0; i < sorted.length; i += COLS) {
    const row = sorted.slice(i, i + COLS)
    const formatted = row.map((v) => `  '${v}',`).join(' ')
    lines.push(formatted)
  }

  lines.push(']')
  lines.push('')
  lines.push(FENCE_CLOSE)
  lines.push('')

  return lines.join('\n')
}

// ── Extract the current generated block from the file ───────────────────

function extractExistingBlock(fileContent: string): string | null {
  const openIdx = fileContent.indexOf(FENCE_OPEN)
  const closeIdx = fileContent.indexOf(FENCE_CLOSE)
  if (openIdx === -1 || closeIdx === -1) return null
  // Return everything between the two fences (inclusive)
  return fileContent.slice(
    openIdx,
    closeIdx + FENCE_CLOSE.length,
  )
}

// ── Normalize a block for comparison (strip volatile lines) ─────────────
//
// We strip the 'Last regenerated:' timestamp line so that --check doesn't
// report false drift just because the timestamp changes on every invocation.
function normalizeBlock(block: string): string {
  return block
    .replace(/\r\n/g, '\n')
    .split('\n')
    .filter((line) => !line.includes('Last regenerated:'))
    .join('\n')
    .trim()
}

// ── Detect drift ───────────────────────────────────────────────────────

function detectDrift(target: string, newBlock: string): boolean {
  if (!existsSync(target)) return true
  const current = readFileSync(target, 'utf8')
  const existing = extractExistingBlock(current)
  if (existing === null) return true  // no block yet → drift
  return normalizeBlock(existing) !== normalizeBlock(newBlock)
}

// ── Replace or append the generated block in the target file ────────────

function applyBlock(target: string, newBlock: string): string {
  if (!existsSync(target)) {
    throw new Error(`Target file not found: ${target}`)
  }

  const current = readFileSync(target, 'utf8')
  const openIdx = current.indexOf(FENCE_OPEN)
  const closeIdx = current.indexOf(FENCE_CLOSE)

  if (openIdx !== -1 && closeIdx !== -1) {
    // Replace existing block (including the newline after the close fence)
    const before = current.slice(0, openIdx)
    const after = current.slice(closeIdx + FENCE_CLOSE.length)
    // Trim trailing whitespace from 'before', then append new block + rest
    return before.replace(/\s*$/, '\n') + newBlock + after
  }

  // No existing block — append at the end of the file
  const separator = current.endsWith('\n') ? '' : '\n'
  return current + separator + newBlock
}

// ── Main ───────────────────────────────────────────────────────────────

function main(): void {
  const args = process.argv.slice(2)
  const mode = args.includes('--write') ? 'write' : 'check'  // --check is the implicit default

  if (!existsSync(CHANNELS_SRC)) {
    console.error(`[ipc-inventory] channels source not found: ${CHANNELS_SRC}`)
    process.exit(1)
  }

  const src = readFileSync(CHANNELS_SRC, 'utf8')
  const values = extractChannelValues(src)

  if (values.length === 0) {
    console.error(
      '[ipc-inventory] No channel values found in channels.ts — regex may be stale.',
    )
    process.exit(1)
  }

  const newBlock = formatBlock(values)

  if (mode === 'check') {
    if (!detectDrift(TARGET_TEST, newBlock)) {
      console.log(
        `[ipc-inventory] OK — ${values.length} channels, no drift detected.`,
      )
      process.exit(0)
    }
    console.error(
      `[ipc-inventory] DRIFT DETECTED — ${values.length} channels in channels.ts ` +
      `but the EXPECTED_CHANNELS block in the test file is stale.`,
    )
    console.error('  Run: bun run gen:ipc-snapshot --write')
    process.exit(1)
  }

  // --write mode
  const updated = applyBlock(TARGET_TEST, newBlock)
  writeFileSync(TARGET_TEST, updated, 'utf8')
  console.log(
    `[ipc-inventory] Wrote ${values.length} channels to ${TARGET_TEST}`,
  )
}

main()
