/**
 * Auto-generated by scripts/check-electron-mock-coverage.ts — DO NOT edit by hand.
 * Consumer files: packages/server-core/src/sessions/SessionManager.ts.
 * Run `bun scripts/check-electron-mock-coverage.ts` to refresh.
 */

export const coverageSnapshot = {
  "BrowserWindow": [],
  "BrowserView": [],
  "WebContents": []
} as const
