/**
 * Auto-generated by scripts/check-electron-mock-coverage.ts — DO NOT edit by hand.
 * Consumer files: apps/electron/src/main/notifications.ts.
 * Run `bun scripts/check-electron-mock-coverage.ts` to refresh.
 */

export const coverageSnapshot = {
  "BrowserWindow": ["focus","isDestroyed","isMinimized","restore","setOverlayIcon","webContents"],
  "BrowserView": [],
  "WebContents": ["id","isDestroyed"]
} as const
